Repository 5-logic/the-sync-backend, pull requests merged in 2025-07, with the labels that each got.

#135 [BE] Implement API get list thesis by lecturerId
  src/domains/theses/dto/update-thesis.dto.ts
  src/domains/theses/thesis.controller.ts
  src/domains/theses/thesis.service.ts
Labels: enhancement

#136 [BE] Implement API get list thesis by lecturerId
  src/domains/theses/dto/update-thesis.dto.ts
  src/domains/theses/thesis.controller.ts
  src/domains/theses/thesis.service.ts
Labels: enhancement

#130 [BE] Implement API change password for admin, lecturer & student
  src/domains/admins/admin.controller.ts
  src/domains/admins/admin.service.ts
  src/domains/admins/dto/update-admin.dto.ts
  src/domains/lecturers/lecturer.controller.ts
  src/domains/lecturers/lecturer.module.ts
  src/domains/students/student.controller.ts
  src/domains/students/student.module.ts
  src/domains/users/dto/update-user.dto.ts
  src/domains/users/user.service.ts
Labels: enhancement

#137 dev: release backend v0.5.6
  scripts/seed.ts
  src/domains/admins/admin.controller.ts
  src/domains/admins/admin.service.ts
  src/domains/admins/dto/update-admin.dto.ts
  src/domains/domain.module.ts
  src/domains/lecturers/lecturer.controller.ts
  src/domains/lecturers/lecturer.module.ts
  src/domains/skill-sets/skill-sets.controller.ts
  src/domains/skill-sets/skill-sets.module.ts
  src/domains/skill-sets/skill-sets.service.ts
  src/domains/students/student.controller.ts
  src/domains/students/student.module.ts
  src/domains/theses/dto/update-thesis.dto.ts
  src/domains/theses/thesis.controller.ts
  src/domains/theses/thesis.service.ts
  src/domains/users/dto/update-user.dto.ts
  src/domains/users/user.service.ts
  tsconfig.json
Labels: enhancement, good first issue

#138 [FE] optimize email notifications and enhance publish/review validation logic
  src/domains/theses/dto/index.ts
  src/domains/theses/dto/publish-theses.dto.ts
  src/domains/theses/dto/update-thesis.dto.ts
  src/domains/theses/thesis.controller.ts
  src/domains/theses/thesis.module.ts
  src/domains/theses/thesis.service.ts
  src/queue/email/enums/type.enum.ts
  src/queue/email/templates/layouts/email-layout.pug
  src/queue/email/templates/send-thesis-status-change.pug
Labels: enhancement

#141 [BE] Add skills when create & update thesis
  src/domains/theses/dto/create-thesis.dto.ts
  src/domains/theses/thesis.service.ts
Labels: enhancement

#147 [BE] Save token to cache & implement API logout
  package.json
  pnpm-lock.yaml
  scripts/seed.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/guards/index.ts
  src/auth/interfaces/cache.interface.ts
  src/auth/interfaces/index.ts
  src/auth/interfaces/payload.interface.ts
  src/auth/strategies/jwt-access.strategy.ts
  src/configs/constant.config.ts
  src/configs/cors.config.ts
  src/domains/lecturers/lecturer.service.ts
  src/domains/majors/major.service.ts
  src/domains/skill-sets/skill-sets.service.ts
  src/domains/students/student.service.ts
  src/main.ts
  src/utils/generator.util.ts
  src/utils/index.ts
Labels: enhancement

#148 [BE] Implement API assign supervisor for thesis & get list group supervise
  docs/environment-setup.md
  src/domains/domain.module.ts
  src/domains/supervisions/dto/assign-supervision.dto.ts
  src/domains/supervisions/dto/change-supervision.dto.ts
  src/domains/supervisions/supervisions.controller.ts
  src/domains/supervisions/supervisions.module.ts
  src/domains/supervisions/supervisions.service.ts
  src/domains/theses/thesis.service.ts
  src/queue/email/enums/type.enum.ts
  src/queue/email/templates/send-supervision-notification.pug
  src/queue/email/templates/send-thesis-status-change.pug
  tsconfig.json
Labels: enhancement

#151 [BE] Implement send OTP & reset password for `users`
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/index.ts
  src/auth/dto/reset-password.dto.ts
  src/domains/users/user.service.ts
  src/queue/email/enums/type.enum.ts
  src/queue/email/templates/send-otp.pug
  src/queue/email/templates/send-reset-password.pug
  src/utils/generator.util.ts
Labels: enhancement

#156 [BE] Implement API Request Invite/Join between Group & Student, update logic for create & update group
  src/domains/domain.module.ts
  src/domains/groups/dto/create-group.dto.ts
  src/domains/groups/dto/update-group.dto.ts
  src/domains/groups/group.service.ts
  src/domains/requests/dto/create-invite-request.dto.ts
  src/domains/requests/dto/create-join-request.dto.ts
  src/domains/requests/dto/index.ts
  src/domains/requests/dto/update-request-status.dto.ts
  src/domains/requests/requests.controller.ts
  src/domains/requests/requests.module.ts
  src/domains/requests/requests.service.ts
  src/queue/email/enums/type.enum.ts
  src/queue/email/templates/send-invite-request-notification.pug
  src/queue/email/templates/send-join-request-notification.pug
  src/queue/email/templates/send-request-status-update.pug
  tsconfig.json
Labels: enhancement

#161 [BE] Update prisma & implemnt API for responsibilities
  prisma/migrations/20250705071441_link_thesis_with_semester/migration.sql
  prisma/schema.prisma
  src/domains/domain.module.ts
  src/domains/requests/request.controller.ts
  src/domains/requests/request.module.ts
  src/domains/requests/request.service.ts
  src/domains/requests/requests.module.ts
  src/domains/responsibilities/responsibility.controller.ts
  src/domains/responsibilities/responsibility.module.ts
  src/domains/responsibilities/responsibility.service.ts
  src/domains/semesters/dto/update-semester.dto.ts
  src/domains/semesters/semester.service.ts
  src/domains/skill-sets/skill-set.controller.ts
  src/domains/skill-sets/skill-set.module.ts
  src/domains/skill-sets/skill-set.service.ts
  src/domains/skill-sets/skill-sets.module.ts
  src/domains/supervisions/supervision.controller.ts
  src/domains/supervisions/supervision.module.ts
  src/domains/supervisions/supervision.service.ts
  src/domains/supervisions/supervisions.module.ts
  src/domains/theses/dto/create-thesis.dto.ts
  src/domains/theses/thesis.service.ts
  tsconfig.json
Labels: enhancement

#167 [BE] Refactor invite request: support inviting multiple students per request & update logic with semester Picking status
  src/domains/groups/group.service.ts
  src/domains/requests/dto/create-invite-request.dto.ts
  src/domains/requests/request.service.ts
  src/domains/semesters/semester.service.ts
  src/domains/students/student.service.ts
Labels: good first issue

#168 [BE] Implement API student, thesis listing APIs and Optimize Thesis GET APIs
  src/domains/groups/group.controller.ts
  src/domains/groups/group.service.ts
  src/domains/students/student.controller.ts
  src/domains/students/student.service.ts
  src/domains/theses/thesis.controller.ts
  src/domains/theses/thesis.service.ts
Labels: good first issue

#169 [BE] Implement API assign student (not grouped) into group & leader remove student
  src/domains/groups/dto/assign-student.dto.ts
  src/domains/groups/dto/index.ts
  src/domains/groups/dto/remove-student.dto.ts
  src/domains/groups/group.controller.ts
  src/domains/groups/group.service.ts
  src/queue/email/enums/type.enum.ts
  src/queue/email/templates/send-group-member-change-notification.pug
Labels: enhancement

#170 [BE] Implement API to assign theses to groups that have already registered
  src/domains/theses/dto/assign-thesis.dto.ts
  src/domains/theses/dto/index.ts
  src/domains/theses/thesis.controller.ts
  src/domains/theses/thesis.service.ts
Labels: enhancement

#171 dev: release API v0.6.0
  src/auth/auth.controller.ts
  src/domains/admins/admin.controller.ts
  src/domains/bases/base-cache.service.ts
  src/domains/groups/dto/assign-student.dto.ts
  src/domains/groups/dto/index.ts
  src/domains/groups/dto/remove-student.dto.ts
  src/domains/groups/group.controller.ts
  src/domains/groups/group.service.ts
  src/domains/lecturers/lecturer.controller.ts
  src/domains/lecturers/lecturer.service.ts
  src/domains/majors/major.controller.ts
  src/domains/majors/major.service.ts
  src/domains/milestones/milestone.controller.ts
  src/domains/milestones/milestone.service.ts
  src/domains/requests/dto/create-invite-request.dto.ts
  src/domains/requests/request.controller.ts
  src/domains/requests/request.service.ts
  src/domains/responsibilities/responsibility.controller.ts
  src/domains/responsibilities/responsibility.service.ts
  src/domains/semesters/semester.controller.ts
  src/domains/semesters/semester.service.ts
  src/domains/skill-sets/skill-set.controller.ts
  src/domains/skill-sets/skill-set.service.ts
  src/domains/students/student.controller.ts
  src/domains/students/student.service.ts
  src/domains/supervisions/supervision.controller.ts
  src/domains/supervisions/supervision.service.ts
  src/domains/theses/dto/assign-thesis.dto.ts
  src/domains/theses/dto/index.ts
  src/domains/theses/thesis.controller.ts
  src/domains/theses/thesis.service.ts
  src/queue/email/enums/type.enum.ts
  src/queue/email/templates/send-group-member-change-notification.pug
  src/queue/email/templates/send-semester-ongoing-notification.pug
  tsconfig.json
Labels: good first issue

#174 [BE] Hotfix Incorrect Dependency Injection Order or Missing @Inject Decorator
  src/domains/groups/group.module.ts
  src/domains/groups/group.service.ts
  src/domains/lecturers/lecturer.service.ts
  src/domains/majors/major.service.ts
  src/domains/milestones/milestone.service.ts
  src/domains/requests/request.service.ts
  src/domains/responsibilities/responsibility.service.ts
  src/domains/semesters/semester.service.ts
  src/domains/skill-sets/skill-set.service.ts
  src/domains/students/student.service.ts
  src/domains/supervisions/supervision.service.ts
  src/domains/theses/thesis.service.ts
Labels: bug

#179 [BE] Implement API pick thesis for group, leave group for member & remove group
  src/domains/groups/dto/index.ts
  src/domains/groups/dto/pick-thesis.dto.ts
  src/domains/groups/group.controller.ts
  src/domains/groups/group.module.ts
  src/domains/groups/group.service.ts
  src/domains/students/student.service.ts
  src/domains/theses/thesis.controller.ts
  src/domains/theses/thesis.module.ts
  src/domains/theses/thesis.service.ts
  src/queue/email/enums/type.enum.ts
  src/queue/email/templates/send-group-deletion-notification.pug
  src/queue/email/templates/send-group-member-change-notification.pug
  src/queue/email/templates/send-thesis-assignment-notification.pug
Labels: enhancement

#183 dev: release API v0.6.3
  prisma/migrations/20250707131611_update_checklist_item_acceptance/migration.sql
  prisma/migrations/20250707134933_add_status_cancelled_into_request_status/migration.sql
  prisma/schema.prisma
  src/auth/auth.controller.ts
  src/common/docs/admin.docs.ts
  src/common/docs/auth.docs.ts
  src/common/docs/checklists.docs.ts
  src/common/docs/group.docs.ts
  src/common/docs/index.ts
  src/common/docs/lecturer.docs.ts
  src/common/docs/major.docs.ts
  src/common/docs/milestone.docs.ts
  src/common/docs/request.docs.ts
  src/common/docs/responsibility.docs.ts
  src/common/docs/semester.docs.ts
  src/common/docs/skill-set.docs.ts
  src/common/docs/student.docs.ts
  src/common/docs/supervision.docs.ts
  src/common/docs/swagger-docs.decorator.ts
  src/common/docs/thesis.docs.ts
  src/domains/admins/admin.controller.ts
  src/domains/bases/base-cache.service.ts
  src/domains/checklists/checklists.controller.ts
  src/domains/checklists/checklists.module.ts
  src/domains/checklists/checklists.service.ts
  src/domains/checklists/dto/create-checklist.dto.ts
  src/domains/checklists/dto/index.ts
  src/domains/checklists/dto/update-checklist.dto.ts
  src/domains/domain.module.ts
  src/domains/groups/group.controller.ts
  src/domains/lecturers/lecturer.controller.ts
  src/domains/lecturers/lecturer.service.ts
  src/domains/majors/major.controller.ts
  src/domains/milestones/milestone.controller.ts
  src/domains/requests/dto/index.ts
  src/domains/requests/request.controller.ts
  src/domains/requests/request.service.ts
  src/domains/responsibilities/responsibility.controller.ts
  src/domains/semesters/semester.controller.ts
  src/domains/skill-sets/skill-set.controller.ts
  src/domains/students/dto/index.ts
  src/domains/students/dto/self-update-student.dto.ts
  src/domains/students/dto/student-expected-responsibility.dto.ts
  src/domains/students/dto/student-skill.dto.ts
  src/domains/students/student.controller.ts
  src/domains/students/student.service.ts
  src/domains/supervisions/dto/index.ts
  src/domains/supervisions/supervision.controller.ts
  src/domains/supervisions/supervision.service.ts
  src/domains/theses/thesis.controller.ts
  tsconfig.json
Labels: enhancement, good first issue

#190 [BE] Implement task 187 & 188
  src/common/docs/admin.docs.ts
  src/common/docs/auth.docs.ts
  src/common/docs/checklist-item.docs.ts
  src/common/docs/checklist.docs.ts
  src/common/docs/group.docs.ts
  src/common/docs/lecturer.docs.ts
  src/common/docs/major.docs.ts
  src/common/docs/milestone.docs.ts
  src/common/docs/request.docs.ts
  src/common/docs/responsibility.docs.ts
  src/common/docs/review.docs.ts
  src/common/docs/semester.docs.ts
  src/common/docs/skill-set.docs.ts
  src/common/docs/student.docs.ts
  src/common/docs/submission.docs.ts
  src/common/docs/supervision.docs.ts
  src/common/docs/thesis.docs.ts
  src/domains/milestones/milestone.service.ts
  src/domains/semesters/dto/index.ts
  src/domains/semesters/dto/update-enrollment.dto.ts
  src/domains/semesters/semester.controller.ts
  src/domains/semesters/semester.service.ts
  src/domains/students/student.service.ts
  src/queue/email/enums/type.enum.ts
  src/queue/email/templates/layouts/email-layout.pug
  src/queue/email/templates/send-enrollment-result-notification.pug
  src/queue/email/templates/send-thesis-assignment-notification.pug
Labels: enhancement

#194 Refactor source code
  src/auth/controllers/admin-auth.controller.ts
  src/auth/controllers/change-password.controller.ts
  src/auth/controllers/password-reset.controller.ts
  src/auth/controllers/user-auth.controller.ts
  src/auth/index.ts
  src/auth/responses/index.ts
  src/auth/responses/login.response.ts
  src/auth/responses/refresh.response.ts
  src/auth/services/admin-auth.service.ts
  src/auth/services/base-auth.service.ts
  src/auth/services/change-password.service.ts
  src/auth/services/password-reset.service.ts
  src/auth/services/token-auth.service.ts
  src/auth/services/user-auth.service.ts
  src/common/decorators/api-array.decorator.ts
  src/common/decorators/api-base.decorator.ts
  src/common/decorators/api-empty.decorator.ts
  src/common/decorators/index.ts
  src/common/index.ts
  src/common/responses/array.response.ts
  src/common/responses/base.response.ts
  src/common/responses/empty.response.ts
  src/common/responses/index.ts
  src/domains/admins/controllers/admin.controller.ts
  src/domains/admins/docs/admin.doc.ts
  src/domains/admins/index.ts
  src/domains/admins/responses/admin.response.ts
  src/domains/admins/responses/index.ts
  src/domains/admins/services/admin.service.ts
  src/domains/lecturers/lecturer.module.ts
  src/domains/majors/controllers/major.controller.ts
  src/domains/majors/index.ts
  src/domains/majors/responses/index.ts
  src/domains/majors/responses/major.response.ts
  src/domains/majors/services/major.service.ts
  src/domains/responsibilities/controllers/responsibility.controller.ts
  src/domains/responsibilities/index.ts
  src/domains/responsibilities/responses/index.ts
  src/domains/responsibilities/responses/responsibility.response.ts
  src/domains/responsibilities/services/responsibility.service.ts
  src/domains/students/student.module.ts
  src/domains/users/index.ts
  src/domains/users/services/index.ts
  src/domains/users/services/user.service.ts
  src/domains/users/user.module.ts
Labels: enhancement

#197 [BE] Hotfix: Validation Rules for Admin, Thesis, Supervision, and Semester Transitions
  src/common/docs/admin.docs.ts
  src/common/docs/group.docs.ts
  src/common/docs/semester.docs.ts
  src/common/docs/supervision.docs.ts
  src/common/docs/thesis.docs.ts
  src/domains/admins/dto/update-admin.dto.ts
  src/domains/admins/services/admin.service.ts
  src/domains/groups/dto/update-group.dto.ts
  src/domains/groups/group.service.ts
  src/domains/semesters/semester.service.ts
  src/domains/submissions/submission.service.ts
  src/domains/supervisions/supervision.service.ts
  src/domains/theses/thesis.service.ts
Labels: bug, good first issue

#204 [BE] Update Logic Reviewer Assignment Validation & Update
  src/common/docs/review.docs.ts
  src/domains/reviews/dto/update-reviewer-assignment.dto.ts
  src/domains/reviews/review.controller.ts
  src/domains/reviews/review.service.ts
Labels: good first issue

#205 [BE] Implement API: Get Reviewer by Group ID & Get Milestones by Semester ID
  src/common/docs/milestone.docs.ts
  src/common/docs/review.docs.ts
  src/domains/milestones/milestone.controller.ts
  src/domains/milestones/milestone.service.ts
  src/domains/reviews/review.controller.ts
  src/domains/reviews/review.service.ts
Labels: enhancement

#198 [BE] Add maxGroup, defaultThesesPerLecturer, and maxThesesPerLecturer to the DTO
  src/domains/semesters/dto/create-semester.dto.ts
  src/domains/semesters/semester.service.ts
Labels: enhancement

#209 [BE] Update logic for Submission module, Milestone Handling Improvements & Submission Enhancements
  prisma/migrations/20250718052219_add_documents_into_model_milestone/migration.sql
  prisma/migrations/20250718052949_update_documents_define_in_milestone/migration.sql
  prisma/schema.prisma
  src/common/docs/milestone.docs.ts
  src/common/docs/submission.docs.ts
  src/domains/milestones/dto/create-milestone.dto.ts
  src/domains/milestones/milestone.service.ts
  src/domains/submissions/submission.controller.ts
  src/domains/submissions/submission.service.ts
Labels: bug, enhancement, good first issue

#210 dev: release api v0.6.9
  prisma/migrations/20250718052219_add_documents_into_model_milestone/migration.sql
  prisma/migrations/20250718052949_update_documents_define_in_milestone/migration.sql
  prisma/schema.prisma
  src/common/docs/milestone.docs.ts
  src/common/docs/submission.docs.ts
  src/domains/milestones/dto/create-milestone.dto.ts
  src/domains/milestones/milestone.service.ts
  src/domains/semesters/dto/create-semester.dto.ts
  src/domains/semesters/semester.service.ts
  src/domains/submissions/submission.controller.ts
  src/domains/submissions/submission.service.ts
Labels: bug, good first issue

#215 [BE] Fix Reviewer Data in Submission Retrieval
  src/domains/reviews/review.service.ts
  src/domains/submissions/submission.service.ts
Labels: bug

#217 [BE] Checklist Creation Logic Enhancement
  src/common/docs/checklist.docs.ts
  src/domains/checklists/checklist.service.ts
Labels: bug

#218 [BE] Milestone Deletion & Update Fixes
  src/common/docs/milestone.docs.ts
  src/domains/milestones/milestone.service.ts
Labels: bug

#229 [BE] Refactor Milestone Module
  prisma/migrations/20250722093712_update_relationship_between_milestone_and_checklist/migration.sql
  prisma/schema.prisma
  src/domains/milestones/constants/index.ts
  src/domains/milestones/constants/milestone.constant.ts
  src/domains/milestones/controllers/index.ts
  src/domains/milestones/controllers/milestone-admin.controller.ts
  src/domains/milestones/controllers/milestone-public.controller.ts
  src/domains/milestones/docs/index.ts
  src/domains/milestones/docs/milestone-admin.doc.ts
  src/domains/milestones/docs/milestone-public.doc.ts
  src/domains/milestones/dto/index.ts
  src/domains/milestones/dtos/create-milestone.dto.ts
  src/domains/milestones/dtos/index.ts
  src/domains/milestones/dtos/update-milestone.dto.ts
  src/domains/milestones/index.ts
  src/domains/milestones/mappers/index.ts
  src/domains/milestones/mappers/milestone.mapper.ts
  src/domains/milestones/milestone.controller.ts
  src/domains/milestones/milestone.module.ts
  src/domains/milestones/milestone.service.ts
  src/domains/milestones/responses/index.ts
  src/domains/milestones/responses/milestone.response.ts
  src/domains/milestones/services/index.ts
  src/domains/milestones/services/milestone-admin.service.ts
  src/domains/milestones/services/milestone-public.service.ts
  src/domains/milestones/services/milestone.service.ts
Labels: duplicate, good first issue

#231 Enhance check duplicate thesis
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/configs/constant.config.ts
  src/configs/email.config.ts
  src/configs/gemini.config.ts
  src/configs/index.ts
  src/configs/jwt-access.config.ts
  src/configs/jwt-refresh.config.ts
  src/configs/redis.config.ts
  src/domains/ai/constants/ai.constant.ts
  src/domains/ai/controllers/ai-thesis.controller.ts
  src/domains/ai/docs/ai-thesis.doc.ts
  src/domains/ai/mappers/duplicate-thesis.mapper.ts
  src/domains/ai/responses/duplicate-thesis.response.ts
  src/domains/ai/services/ai-thesis.service.ts
  src/providers/gemini/gemini-provider.module.ts
  src/providers/gemini/index.ts
  src/providers/gemini/services/gemini-provider.service.ts
  src/providers/gemini/services/index.ts
  src/providers/index.ts
  src/queue/pinecone/processors/pinecone-thesis.processor.ts
  src/utils/cache.util.ts
  src/utils/index.ts
  src/utils/pinecone.util.ts
  src/utils/redis.util.ts
Labels: bug

#235 [BE] Hotfix round 2
  prisma/migrations/20250725024909_add_note_into_model_milestone/migration.sql
  prisma/schema.prisma
  src/domains/groups/group.controller.ts
  src/domains/groups/group.service.ts
  src/domains/lecturers/services/lecturer-management.service.ts
  src/domains/milestones/dtos/create-milestone.dto.ts
  src/domains/reviews/review.controller.ts
  src/domains/reviews/review.service.ts
  src/domains/students/services/student-admin.service.ts
  src/domains/supervisions/supervision.service.ts
  src/domains/theses/services/thesis-lecturer.service.ts
  src/domains/theses/services/thesis-moderator.service.ts
Labels: bug, good first issue

#237 [BE] Hotfix round 4
  src/common/docs/supervision.docs.ts
  src/domains/semesters/controllers/semester.controller.ts
  src/domains/semesters/docs/semester-enrollment.doc.ts
  src/domains/semesters/docs/semester.doc.ts
  src/domains/semesters/services/semester-enrollment.service.ts
  src/domains/semesters/services/semester-status.service.ts
  src/domains/semesters/services/semester.service.ts
  src/domains/supervisions/supervision.controller.ts
  src/domains/supervisions/supervision.service.ts
Labels: bug, good first issue

#240 Implement AI API
  CHANGELOG.md
  src/domains/ai/ai.module.ts
  src/domains/ai/constants/ai.constant.ts
  src/domains/ai/controllers/ai-student.controller.ts
  src/domains/ai/controllers/ai-thesis.controller.ts
  src/domains/ai/controllers/index.ts
  src/domains/ai/docs/ai-student.doc.ts
  src/domains/ai/docs/ai-thesis.doc.ts
  src/domains/ai/docs/index.ts
  src/domains/ai/responses/index.ts
  src/domains/ai/responses/student-suggestion.response.ts
  src/domains/ai/services/ai-student.service.ts
  src/domains/ai/services/ai-thesis.service.ts
  src/domains/ai/services/index.ts
  src/domains/groups/controllers/group-moderator.controller.ts
  src/domains/groups/controllers/group-public.controller.ts
  src/domains/groups/controllers/group-student.controller.ts
  src/domains/groups/controllers/index.ts
  src/domains/groups/group.service.ts
  src/domains/groups/mappers/group-detail.mapper.ts
  src/domains/groups/mappers/group.mapper.ts
  src/domains/groups/mappers/index.ts
  src/domains/groups/responses/group-detail.response.ts
  src/domains/groups/responses/group.response.ts
  src/domains/groups/responses/index.ts
  src/domains/groups/services/group-moderator.service.ts
  src/domains/groups/services/group-public.service.ts
  src/domains/groups/services/group-student.service.ts
  src/domains/groups/services/index.ts
  src/domains/requests/request.service.ts
  src/domains/semesters/controllers/semester.controller.ts
  src/domains/semesters/docs/semester.doc.ts
  src/domains/semesters/services/semester.service.ts
  src/domains/students/services/student-admin.service.ts
  src/domains/students/services/student-self.service.ts
  src/queue/pinecone/constants/pinecone.constant.ts
  src/queue/pinecone/pinecone.module.ts
  src/queue/pinecone/processors/index.ts
  src/queue/pinecone/processors/pinecone-group.processor.ts
  src/queue/pinecone/processors/pinecone-student.processor.ts
  src/queue/pinecone/processors/pinecone-thesis.processor.ts
  src/queue/pinecone/services/index.ts
  src/queue/pinecone/services/pinecone-group.service.ts
  src/queue/pinecone/services/pinecone-student.service.ts
Labels: enhancement

#242 [BE] Refactor folder structure for Checklist Module & fix some bug
  src/domains/checklists/checklist.controller.ts
  src/domains/checklists/checklist.module.ts
  src/domains/checklists/constants/checklist.constant.ts
  src/domains/checklists/constants/index.ts
  src/domains/checklists/controllers/checklist-lecturer.controller.ts
  src/domains/checklists/controllers/checklist-moderator.controller.ts
  src/domains/checklists/controllers/index.ts
  src/domains/checklists/docs/checklist-lecturer.doc.ts
  src/domains/checklists/docs/checklist-moderator.doc.ts
  src/domains/checklists/docs/index.ts
  src/domains/checklists/dto/index.ts
  src/domains/checklists/dtos/create-checklist.dto.ts
  src/domains/checklists/dtos/index.ts
  src/domains/checklists/dtos/update-checklist.dto.ts
  src/domains/checklists/index.ts
  src/domains/checklists/services/checklist-lecturer.service.ts
  src/domains/checklists/services/checklist-moderator.service.ts
  src/domains/checklists/services/checklist.service.ts
  src/domains/checklists/services/index.ts
  src/domains/groups/group.service.ts
  src/domains/milestones/dtos/create-milestone.dto.ts
Labels: bug, enhancement, good first issue

#243 [BE] Refactor folder structure for Checklist Item Module
  src/domains/checklists/checklist-items/checklist-item.controller.ts
  src/domains/checklists/checklist-items/checklist-item.module.ts
  src/domains/checklists/checklist-items/checklist-item.service.ts
  src/domains/checklists/checklist-items/constants/checklist-item.constant.ts
  src/domains/checklists/checklist-items/constants/index.ts
  src/domains/checklists/checklist-items/controllers/checklist-item-lecturer.controller.ts
  src/domains/checklists/checklist-items/controllers/checklist-item-moderator.controller.ts
  src/domains/checklists/checklist-items/controllers/index.ts
  src/domains/checklists/checklist-items/docs/checklist-item-lecturer.doc.ts
  src/domains/checklists/checklist-items/docs/checklist-item-moderator.doc.ts
  src/domains/checklists/checklist-items/docs/index.ts
  src/domains/checklists/checklist-items/dto/index.ts
  src/domains/checklists/checklist-items/dtos/create-checklist-item.dto.ts
  src/domains/checklists/checklist-items/dtos/create-many-checklist-item.dto.ts
  src/domains/checklists/checklist-items/dtos/index.ts
  src/domains/checklists/checklist-items/dtos/update-checklist-item.dto.ts
  src/domains/checklists/checklist-items/dtos/update-many-checklist-item.dto.ts
  src/domains/checklists/checklist-items/index.ts
  src/domains/checklists/checklist-items/services/checklist-item-lecturer.service.ts
  src/domains/checklists/checklist-items/services/checklist-item-moderator.service.ts
  src/domains/checklists/checklist-items/services/index.ts
  src/domains/checklists/checklist.module.ts
  src/domains/checklists/services/checklist-moderator.service.ts
Labels: bug, duplicate, good first issue

#248 [BE] Refactor folder structure for Supervision Module
  src/domains/supervisions/constants/index.ts
  src/domains/supervisions/constants/supervision.constant.ts
  src/domains/supervisions/controllers/index.ts
  src/domains/supervisions/controllers/supervision-moderator.controller.ts
  src/domains/supervisions/controllers/supervision-public.controller.ts
  src/domains/supervisions/docs/index.ts
  src/domains/supervisions/docs/supervision-moderator.doc.ts
  src/domains/supervisions/docs/supervision-public.doc.ts
  src/domains/supervisions/dto/index.ts
  src/domains/supervisions/dtos/assign-bulk-supervision.dto.ts
  src/domains/supervisions/dtos/change-supervision.dto.ts
  src/domains/supervisions/dtos/index.ts
  src/domains/supervisions/index.ts
  src/domains/supervisions/services/index.ts
  src/domains/supervisions/services/supervision-moderator.service.ts
  src/domains/supervisions/services/supervision-public.service.ts
  src/domains/supervisions/services/supervision.service.ts
  src/domains/supervisions/supervision.controller.ts
  src/domains/supervisions/supervision.module.ts
  src/domains/supervisions/supervision.service.ts
Labels: duplicate, good first issue
