Repository 5-logic/the-sync-backend, pull requests merged in 2025-06, with the labels that each got.

#39 [BE] Implemnt API response template
  Dockerfile
  src/filters/http-exception/http-exception.filter.ts
  src/interceptors/transform/transform.interceptor.ts
  src/main.ts
  tsconfig.json
Labels: enhancement

#44 [BE] Fix create student
  package.json
  prisma/migrations/20250616021811_fix_relationship_between_student_and_enrollment/migration.sql
  prisma/schema.prisma
  src/domains/students/student.service.ts
  src/domains/users/dto/create-user.dto.ts
Labels: bug, enhancement

#56 [BE] Fix some bugs from production
  src/auth/auth.service.ts
  src/domains/admins/admin.service.ts
  src/domains/admins/dto/update-admin.dto.ts
  src/domains/lecturers/dto/update-lecturer.dto.ts
  src/domains/lecturers/lecturer.service.ts
  src/domains/students/dto/update-student.dto.ts
  src/domains/students/student.service.ts
  src/domains/users/dto/create-user.dto.ts
  src/domains/users/dto/update-user.dto.ts
  src/domains/users/user.service.ts
Labels: bug

#58 [BE] Authorize for API
  package.json
  pnpm-lock.yaml
  prisma/migrations/20250618071908_some_stuffs_change/migration.sql
  src/auth/auth.module.ts
  src/auth/decorators/roles.decorator.ts
  src/auth/guards/jwt-access.guard.ts
  src/auth/guards/role.guard.ts
  src/auth/interfaces/user-payload.interface.ts
  src/auth/strategies/jwt-access.strategy.ts
  src/domains/admins/admin.controller.ts
  src/domains/lecturers/lecturer.controller.ts
  src/domains/semesters/semester.controller.ts
  src/domains/students/student.controller.ts
  src/swagger/setup.ts
Labels: enhancement

#59 [BE] Authorize for API
  package.json
  pnpm-lock.yaml
  prisma/migrations/20250618071908_some_stuffs_change/migration.sql
  src/auth/auth.module.ts
  src/auth/decorators/roles.decorator.ts
  src/auth/guards/jwt-access.guard.ts
  src/auth/guards/role.guard.ts
  src/auth/interfaces/user-payload.interface.ts
  src/auth/strategies/jwt-access.strategy.ts
  src/domains/admins/admin.controller.ts
  src/domains/lecturers/lecturer.controller.ts
  src/domains/semesters/semester.controller.ts
  src/domains/students/student.controller.ts
  src/swagger/setup.ts
Labels: enhancement

#65 [BE] Implement API for Thesis
  package.json
  pnpm-lock.yaml
  prisma/migrations/20250617161640_set_status_is_default_for_thesis/migration.sql
  prisma/migrations/20250618071908_some_stuffs_change/migration.sql
  prisma/schema.prisma
  src/domains/domain.module.ts
  src/domains/lecturers/dto/update-lecturer.dto.ts
  src/domains/lecturers/lecturer.controller.ts
  src/domains/lecturers/lecturer.service.ts
  src/domains/semesters/semester.controller.ts
  src/domains/students/dto/update-student.dto.ts
  src/domains/students/student.controller.ts
  src/domains/students/student.service.ts
  src/domains/theses/dto/create-thesis.dto.ts
  src/domains/theses/dto/update-thesis.dto.ts
  src/domains/theses/thesis.controller.ts
  src/domains/theses/thesis.module.ts
  src/domains/theses/thesis.service.ts
  src/domains/users/dto/update-user.dto.ts
  tsconfig.json
Labels: enhancement

#77 [BE] Implement API for `majors`
  src/domains/domain.module.ts
  src/domains/majors/major.controller.ts
  src/domains/majors/major.module.ts
  src/domains/majors/major.service.ts
  tsconfig.json
Labels: enhancement

#79 [BE] Re-write workflow publish Docker image
  .github/workflows/release-and-publish.yml
Labels: enhancement

#80 [BE] More logic for API about `semesters`
  src/domains/semesters/dto/create-semester.dto.ts
  src/domains/semesters/dto/update-semester.dto.ts
  src/domains/semesters/semester.controller.ts
  src/domains/semesters/semester.service.ts
Labels: enhancement

#81 [BE] More logic for API about `lecturers`
  prisma/migrations/20250621183629_remove_timestamp_in_lecturer_model/migration.sql
  prisma/schema.prisma
  src/domains/lecturers/dto/toggle-lecturer-status.dto.ts
  src/domains/lecturers/dto/update-lecturer.dto.ts
  src/domains/lecturers/lecturer.controller.ts
  src/domains/lecturers/lecturer.service.ts
  src/domains/users/dto/create-user.dto.ts
  src/domains/users/dto/update-user.dto.ts
Labels: enhancement

#82 [BE] More logic for API about `students`
  prisma/migrations/20250621194510_remove_timestamp_in_student_model/migration.sql
  prisma/migrations/20250621200149_enable_force_remove_when_remove_a_student_for_enrollments/migration.sql
  prisma/schema.prisma
  src/domains/students/dto/toggle-student-status.dto.ts
  src/domains/students/dto/update-student.dto.ts
  src/domains/students/student.controller.ts
  src/domains/students/student.service.ts
Labels: enhancement

#88 [BE] More logic for API about `groups`
  scripts/seed.ts
  src/domains/groups/dto/create-group.dto.ts
  src/domains/groups/dto/update-group.dto.ts
  src/domains/groups/group.controller.ts
  src/domains/groups/group.service.ts
Labels: enhancement

#84 [BE] Add more logicial for API about `theses`, `groups`, `lecturers`, `students`, `milestones`, `semesters`
  prisma/migrations/20250622172507_enable_force_remove_a_thesis/migration.sql
  prisma/schema.prisma
  scripts/seed.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/domains/admins/admin.controller.ts
  src/domains/admins/admin.service.ts
  src/domains/groups/dto/create-group.dto.ts
  src/domains/groups/dto/update-group.dto.ts
  src/domains/groups/group.controller.ts
  src/domains/groups/group.service.ts
  src/domains/lecturers/lecturer.controller.ts
  src/domains/lecturers/lecturer.service.ts
  src/domains/milestones/dto/create-milestone.dto.ts
  src/domains/milestones/dto/update-milestone.dto.ts
  src/domains/milestones/milestone.controller.ts
  src/domains/milestones/milestone.service.ts
  src/domains/semesters/semester.controller.ts
  src/domains/semesters/semester.service.ts
  src/domains/students/student.controller.ts
  src/domains/students/student.service.ts
  src/domains/theses/dto/create-thesis.dto.ts
  src/domains/theses/dto/review-thesis.dto.ts
  src/domains/theses/thesis.controller.ts
  src/domains/theses/thesis.service.ts
  src/domains/users/user.service.ts
Labels: enhancement

#93 [BE] Fix API import students
  package.json
  src/domains/milestones/dto/create-milestone.dto.ts
  src/domains/students/dto/create-student.dto.ts
  src/domains/students/dto/import-student.dto.ts
  src/domains/students/student.controller.ts
  src/domains/students/student.service.ts
  src/main.ts
Labels: bug

#94 [BE] Add API get all student per semester
  src/domains/students/student.controller.ts
  src/domains/students/student.service.ts
Labels: enhancement

#104 [BE] Implement BullMQ for backend
  docs/environment-setup.md
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/guards/jwt-access.guard.ts
  src/auth/strategies/jwt-access.strategy.ts
  src/configs/cors.config.ts
  src/configs/index.ts
  src/configs/jwt-access.config.ts
  src/configs/jwt-refresh.config.ts
  src/configs/redis.config.ts
  src/configs/token.config.ts
  src/domains/admins/admin.controller.ts
  src/domains/milestones/milestone.controller.ts
  src/domains/milestones/milestone.service.ts
  src/domains/semesters/semester.controller.ts
  src/domains/semesters/semester.service.ts
  src/domains/students/student.service.ts
  src/domains/theses/thesis.service.ts
  src/main.ts
  src/swagger/setup.ts
  tsconfig.json
Labels: enhancement

#107 [BE] Edit `Dockerfile`
  .dockerignore
  .github/workflows/release-and-publish.yml
  Dockerfile
Labels: enhancement

#112 [BE] Fix docker image missing openssl library
  Dockerfile
Labels: bug

#117 [BE] Add API udpate for `students` and `lecturers` by admin
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dto/index.ts
  src/auth/index.ts
  src/domains/admins/admin.controller.ts
  src/domains/admins/admin.service.ts
  src/domains/admins/dto/index.ts
  src/domains/groups/dto/index.ts
  src/domains/groups/group.controller.ts
  src/domains/groups/group.service.ts
  src/domains/lecturers/dto/index.ts
  src/domains/lecturers/dto/update-lecturer.dto.ts
  src/domains/lecturers/lecturer.controller.ts
  src/domains/lecturers/lecturer.service.ts
  src/domains/majors/major.controller.ts
  src/domains/milestones/dto/index.ts
  src/domains/milestones/milestone.controller.ts
  src/domains/milestones/milestone.service.ts
  src/domains/semesters/dto/index.ts
  src/domains/semesters/semester.controller.ts
  src/domains/semesters/semester.service.ts
  src/domains/students/dto/index.ts
  src/domains/students/dto/self-update-student.dto.ts
  src/domains/students/dto/update-student.dto.ts
  src/domains/students/student.controller.ts
  src/domains/students/student.service.ts
  src/domains/theses/dto/index.ts
  src/domains/theses/thesis.controller.ts
  src/domains/theses/thesis.service.ts
  src/domains/users/dto/index.ts
  src/domains/users/user.service.ts
Labels: enhancement

#120 [BE] Fix CORS
  src/configs/cors.config.ts
  src/main.ts
  src/middlewares/bull-board/bull-board.middleware.ts
Labels: bug

#127 [BE] Fix prisma error when run transactions
  package.json
  pnpm-lock.yaml
  prisma/migrations/20250630055205_set_default_for_enrollment/migration.sql
  prisma/schema.prisma
  scripts/seed.ts
  src/app.module.ts
  src/auth/dto/auth.admin.dto.ts
  src/auth/dto/auth.user.dto.ts
  src/configs/constant.config.ts
  src/configs/cors.config.ts
  src/domains/groups/group.controller.ts
  src/domains/lecturers/lecturer.controller.ts
  src/domains/lecturers/lecturer.service.ts
  src/domains/students/student.controller.ts
  src/domains/students/student.service.ts
  src/domains/theses/thesis.controller.ts
  src/domains/users/user.service.ts
  src/filters/http-exception/http-exception.filter.ts
  src/interceptors/logging/logging.interceptor.ts
  src/interceptors/transform/transform.interceptor.ts
  src/main.ts
  src/middlewares/bull-board/bull-board.middleware.ts
  src/middlewares/index.ts
  src/providers/prisma/prisma.module.ts
  src/types/fastify-request.d.ts
  src/utils/password-generator.util.ts
Labels: enhancement

#129 [BE] Implement API change password for admin, lecturer & student
  src/domains/admins/admin.controller.ts
  src/domains/admins/admin.service.ts
  src/domains/admins/dto/update-admin.dto.ts
  src/domains/lecturers/lecturer.controller.ts
  src/domains/lecturers/lecturer.module.ts
  src/domains/students/student.controller.ts
  src/domains/students/student.module.ts
  src/domains/users/dto/update-user.dto.ts
  src/domains/users/user.service.ts
Labels: enhancement
